# THis is the Main Hugo Configuration File.
# For more information, please see https://gohugo.io/getting-started/configuration/
baseURL: 'https://elclaustro.cl/'
languageCode: es-es
title: El Claustro
theme: ananke
url: https://elclaustro.cl
name: El Claustro
description: Cultura Dark, Gótica y Alternativa
paginate: 10
enableRobotsTXT: true
defaultContentLanguage: es
enableGitInfo: true
enableInlineShortcodes: true
