# THis is the Main Hugo Configuration File.
# For more information, please see https://gohugo.io/getting-started/configuration/
baseURL: 'https://gh.elclaustro.cl/'
languageCode: es-es
title: El Claustro
theme: ananke
url: https://gh.elclaustro.cl
name: El Claustro
description: Cultura Dark, Gótica y Alternativa
paginate: 3
enableRobotsTXT: true
defaultContentLanguage: es
enableGitInfo: true
enableInlineShortcodes: true
permalinks:
  posts: /:title/
mediaTypes:
  - application/javascript
  - application/json
  - application/xml
  - application/rss+xml
  - application/atom+xml
  - application/rdf+xml
  - application/ld+json
  - application/x-web-app-manifest+json
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: true
resourceDir: resources
DefaultContentLanguage: es
SectionPagesMenu: main
Paginate: 10
googleAnalytics: ''
languages:
  es:
    title: El Claustro
    weight: 1
    contentDir: content
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  AuthorName: Nicolas Georger
  GitHubUser: ngeorger
  SidebarRecentLimit: 5
  Subtitle: Cultura Dark, Gótica y Alternativa
  text_color: ''
  author: ''
  favicon: 'favicon.ico'
  site_logo: 'logo.png'
  description: Cultura Dark, Gótica y Alternativa
  background_color_class: bg-black
  recent_posts_number: 10

  ananke_socials:
    - name: instagram
      url: 'https://www.instagram.com/elclaustrocl'
    - name: youtube
      url: 'https://www.youtube.com/@elclaustrocl'
    - name: facebook
      url: 'https://www.facebook.com/elclaustrocl'
    - name: twitter
      url: 'https://www.twitter.com/elclaustrocl'
    - name: github
      url: 'https://www.github.com/sredevopsdev/elclaustro'

