# THis is the Main Hugo Configuration File.
# For more information, please see https://gohugo.io/getting-started/configuration/
baseURL: 'https://gh.elclaustro.cl/'
languageCode: es-es
title: El Claustro
theme: ananke
url: https://gh.elclaustro.cl
name: El Claustro
description: Cultura Dark, Gótica y Alternativa
paginate: 10
enableRobotsTXT: true
defaultContentLanguage: es
enableGitInfo: true
enableInlineShortcodes: true
params:
  AuthorName: Nicolas Georger
  GitHubUser: ngeorger
  SidebarRecentLimit: 5
  Subtitle: Cultura Dark, Gótica y Alternativa
permalinks:
  posts: /:title/
mediaTypes:
  - application/javascript
  - application/json
  - application/xml
  - application/rss+xml
  - application/atom+xml
  - application/rdf+xml
  - application/ld+json
  - application/x-web-app-manifest+json
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
  - application/x-font-truetype
  - application/x-font-ttf
  - application/x-font-opentype
  - application/vnd.ms-fontobject
  - application/x-font-woff
  - application/x-font-woff2
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: true
