
baseurl: 'https://elclaustro.cl/'
title: El Claustro
theme: newsroom
# author: Weru
copyright: 'Copyleft.'
canonifyurls: true
paginate: 10


markup:
  goldmark:
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: true
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: false
    tabWidth: 2
    disqusShortname: elclaustrocl
# params:
# # THis is the Main Hugo Configuration File.
# # For more information, please see https://gohugo.io/getting-started/configuration/
baseURL: 'https://elclaustro.cl/'
languageCode: es-CL
url: https://elclaustro.cl
name: El Claustro
description: Difundimos Cultura Dark, G贸tica y Alternativa
enableRobotsTXT: true
defaultContentLanguage: es
enableGitInfo: true
enableInlineShortcodes: true
# default hugo permalinks 
permalinks:
  posts: /categoria/:slug/:title/
  pages: /:title/
  section: /:section/
  taxonomies: /:section/:slug/
  year: /:year/
  month: /:year/:month/
  day: /:year/:month/:day/
  tag: /tag/:slug/
  category: /categoria/:slug/
# permalinks:
# permalinks:
#   posts: /:title/
#   pages: /:title/
#   section: /:section/
#   taxonomies: /:section/:slug/
#   year: /:year/
#   month: /:year/:month/
#   day: /:year/:month/:day/
#   tag: /tag/:slug/
#   category: /categoria/:slug/

resourceDir: resources
DefaultContentLanguage: es
SectionPagesMenu: main
Paginate: 10
# googleAnalytics: 'UA-1838316-1'
sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
params:
#   body_classes: 'avenir bg-near-black light-gray'
#   text_color: 'light-gray'
  AuthorName: Nicolas Georger
  GitHubUser: ngeorger
  SiteTitle: El Claustro
  Subtitle: Difundimos Cultura Dark, G贸tica y Alternativa
  author: 'Nicolas Georger'
  favicon: 'favicon.ico'
  site_logo: 'logo.png'
  logo: 'logo.png'
  description: Difundimos Cultura Dark, G贸tica y Alternativa
  summary: Difundimos Cultura Dark, G贸tica y Alternativa
#   show_sidebar: false
#   show_reading_time: true
#   recent_posts_number: 4
#   recent_posts_title: Recientes
#   recent_posts_show_date: false
#   breadcrumbs: true
  locale: es-es
  keywords: 'El Claustro'
  ga_analytics: 'UA-1838316-1'
#   ga_verify: ''
  instagram: 'elclaustrocl'
  twitter: 'elclaustro'
  twitter_card: 'summary'
  twitter_creator: 'elclaustro'

  mainSections:
    - post
    # - page
  disableDarkMode: false

#   ananke_socials:
#     - name: instagram
#       url: 'https://www.instagram.com/elclaustrocl'
#     - name: youtube
#       url: 'https://www.youtube.com/@elclaustrocl'
#     - name: facebook
#       url: 'https://www.facebook.com/elclaustrocl'
#     - name: twitter
#       url: 'https://www.twitter.com/elclaustro'
#     - name: github
#       url: 'https://www.github.com/sredevopsdev/elclaustro'
#     - name: rss
#       url: 'https://elclaustro.cl/index.xml'
