name: Publicar
title: "Publicación: "
labels: ["publicación"]
assignees: ["@ngeorger"]
description: "Publicar contenido en ElClaustro.cl"
body: 
  - type: markdown
    attributes:
      value: |
        ¡Hola! Gracias por querer publicar en ElClaustro.cl. Por favor, completa el siguiente formulario para que podamos revisar tu contenido y publicarlo en el sitio.
  - type: input
    id: contact
    attributes:
      label: Datos de contacto
      description: Cómo podemos contactarnos contigo?
      placeholder: "Correo, Instagram, etc"
    validations:
      required: true
  - type: input
    id: titulo
    attributes:
      label: Título
      description: El título de tu contenido
      placeholder: "Escribe el título aquí"
    validations:
      required: true
  - type: textarea
    id: resumen
    attributes:
      label: Resumen del contenido
      description: Describe brevemente de qué trata tu contenido (Opcional)
      placeholder: Cuéntanos sobre tu post
      value: "Quiero publicar esta noticia!"
    validations:
      required: false
  - type: dropdown
    id: categoria
    attributes:
      label: Categoría
      description: En qué categoría va tu contenido?
      options:
        - Noticias
        - Discos Y Multimedia
        - Entrevistas
        - Columnas
    validations:
      required: true
  - type: textarea
    id: contenido
    attributes:
      label: Contenido
      description: El contenido de tu mensaje
      placeholder: "Escribe tu contenido aquí"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
